services:
  docker-server:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      jenkins-net:
        aliases:
          - docker
    ports:
      - 2376:2376
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./docker-certs:/certs/client

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - docker-server
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./docker-certs:/certs/client:ro
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins-net

networks:
  jenkins-net:
